export const NpcName = [
  'Skeleton',
  'Returned',
  'BoneWarrior',
  'BurningDead',
  'Horror',
  'Zombie',
  'HungryDead',
  'Ghoul',
  'DrownedCarcass',
  'PlagueBearer',
  'Afflicted',
  'Tainted',
  'Misshapen',
  'Disfigured',
  'Damned',
  'FoulCrow',
  'BloodHawk',
  'BlackRaptor',
  'CloudStalker',
  'Fallen',
  'Carver',
  'Devilkin',
  'DarkOne',
  'WarpedFallen',
  'Brute',
  'Yeti',
  'Crusher',
  'WailingBeast',
  'GargantuanBeast',
  'SandRaider',
  'Marauder',
  'Invader',
  'Infidel',
  'Assailant',
  'unused',
  'unused',
  'unused',
  'unused',
  'Ghost',
  'Wraith',
  'Specter',
  'Apparition',
  'DarkShape',
  'DarkHunter',
  'VileHunter',
  'DarkStalker',
  'BlackRogue',
  'FleshHunter',
  'DuneBeast',
  'RockDweller',
  'JungleHunter',
  'DoomApe',
  'TempleGuard',
  'MoonClan',
  'NightClan',
  'BloodClan',
  'HellClan',
  'DeathClan',
  'FallenShaman',
  'CarverShaman',
  'DevilkinShaman',
  'DarkShaman',
  'WarpedShaman',
  'QuillRat',
  'SpikeFiend',
  'ThornBeast',
  'RazorSpine',
  'JungleUrchin',
  'SandMaggot',
  'RockWorm',
  'Devourer',
  'GiantLamprey',
  'WorldKiller',
  'TombViper',
  'ClawViper',
  'Salamander',
  'PitViper',
  'SerpentMagus',
  'SandLeaper',
  'CaveLeaper',
  'TombCreeper',
  'TreeLurker',
  'RazorPitDemon',
  'Huntress',
  'SaberCat',
  'NightTiger',
  'HellCat',
  'Itchies',
  'BlackLocusts',
  'PlagueBugs',
  'HellSwarm',
  'DungSoldier',
  'SandWarrior',
  'Scarab',
  'SteelWeevil',
  'AlbinoRoach',
  'DriedCorpse',
  'Decayed',
  'Embalmed',
  'PreservedDead',
  'Cadaver',
  'HollowOne',
  'Guardian',
  'Unraveler',
  'Horadrim Ancient',
  'Baal Subject Mummy',
  'unused',
  'unused',
  'unused',
  'unused',
  'CarrionBird',
  'UndeadScavenger',
  'HellBuzzard',
  'WingedNightmare',
  'Sucker',
  'Feeder',
  'BloodHook',
  'BloodWing',
  'Gloam',
  'SwampGhost',
  'BurningSoul',
  'BlackSoul',
  'Arach',
  'SandFisher',
  'PoisonSpinner',
  'FlameSpider',
  'SpiderMagus',
  'ThornedHulk',
  'BrambleHulk',
  'Thrasher',
  'Spikefist',
  'GhoulLord',
  'NightLord',
  'DarkLord',
  'BloodLord',
  'Banished',
  'DesertWing',
  'Fiend',
  'Gloombat',
  'BloodDiver',
  'DarkFamiliar',
  'RatMan',
  'Fetish',
  'Flayer',
  'SoulKiller',
  'StygianDoll',
  'DeckardCain',
  'Gheed',
  'Akara',
  'dummy',
  'Kashya',
  'dummy',
  'Dummy',
  'Dummy',
  'Charsi',
  'Warriv',
  'Andariel',
  'dummy',
  'dummy',
  'dummy',
  'DarkRanger',
  'VileArcher',
  'DarkArcher',
  'BlackArcher',
  'FleshArcher',
  'DarkSpearwoman',
  'VileLancer',
  'DarkLancer',
  'BlackLancer',
  'FleshLancer',
  'SkeletonArcher',
  'ReturnedArcher',
  'BoneArcher',
  'BurningDeadArcher',
  'HorrorArcher',
  'Warriv',
  'Atma',
  'Drognan',
  'Fara',
  'dummy',
  'SandMaggotYoung',
  'RockWormYoung',
  'DevourerYoung',
  'GiantLampreyYoung',
  'WorldKillerYoung',
  'dummy',
  'Blunderbore',
  'Gorbelly',
  'Mauler',
  'Urdar',
  'SandMaggotEgg',
  'RockWormEgg',
  'DevourerEgg',
  'GiantLampreyEgg',
  'WorldKillerEgg',
  'dummy',
  'Dummy',
  'dummy',
  'Greiz',
  'Elzix',
  'Geglash',
  'Jerhyn',
  'Lysander',
  'Dummy',
  'dummy',
  'dummy',
  'FoulCrowNest',
  'BloodHawkNest',
  'BlackVultureNest',
  'CloudStalkerNest',
  'Meshif',
  'Duriel',
  'Undead RatMan',
  'Undead Fetish',
  'Undead Flayer',
  'Undead SoulKiller',
  'Undead StygianDoll',
  'unused',
  'unused',
  'unused',
  'unused',
  'unused',
  'unused',
  'unused',
  'unused',
  'unused',
  'unused',
  'Maggot',
  'MummyGenerator',
  'Radament',
  'unused',
  'unused',
  'unused',
  'unused',
  'FlyingScimitar',
  'Zakarumite',
  'Faithful',
  'Zealot',
  'Sexton',
  'Cantor',
  'Heirophant',
  'Heirophant',
  'Mephisto',
  'Diablo',
  'DeckardCain',
  'DeckardCain',
  'DeckardCain',
  'Swamp Dweller',
  'Bog Creature',
  'Slime Prince',
  'Summoner',
  'tyrael',
  'asheara',
  'hratli',
  'alkor',
  'ormus',
  'izual',
  'halbu',
  'WaterWatcherLimb',
  'RiverStalkerLimb',
  'StygianWatcherLimb',
  'WaterWatcherHead',
  'RiverStalkerHead',
  'StygianWatcherHead',
  'meshif',
  'DeckardCain',
  'navi',
  'Bloodraven',
  'Dummy',
  'Dummy',
  'RogueScout',
  'Dummy',
  'Dummy',
  'GargoyleTrap',
  'ReturnedMage',
  'BoneMage',
  'BurningDeadMage',
  'HorrorMage',
  'RatManShaman',
  'FetishShaman',
  'FlayerShaman',
  'SoulKillerShaman',
  'StygianDollShaman',
  'larva',
  'SandMaggotQueen',
  'RockWormQueen',
  'DevourerQueen',
  'GiantLampreyQueen',
  'WorldKillerQueen',
  'ClayGolem',
  'BloodGolem',
  'IronGolem',
  'FireGolem',
  'Dummy',
  'Dummy',
  'NightMarauder',
  'Dummy',
  'Natalya',
  'FleshSpawner',
  'StygianHag',
  'Grotesque',
  'FleshBeast',
  'StygianDog',
  'GrotesqueWyrm',
  'Groper',
  'Strangler',
  'StormCaster',
  'Corpulent',
  'CorpseSpitter',
  'MawFiend',
  'DoomKnight',
  'AbyssKnight',
  'OblivionKnight',
  'QuillBear',
  'SpikeGiant',
  'ThornBrute',
  'RazorBeast',
  'GiantUrchin',
  'Dummy',
  'Dummy',
  'Dummy',
  'Dummy',
  'Dummy',
  'Dummy',
  'Dummy',
  'Dummy',
  'a trap',
  'a trap',
  'a trap',
  'a trap',
  'a trap',
  'Kaelan',
  'Dummy',
  'dclone',
  'SuckerNest',
  'FeederNest',
  'BloodHookNest',
  'BloodWingNest',
  'Guard',
  'Dummy',
  '',
  '',
  '',
  '',
  'Dummy',
  'Council Member',
  'Council Member',
  'Council Member',
  'Turret',
  'Turret',
  'Turret',
  'Hydra',
  'Hydra',
  'Hydra',
  'a trap',
  'Dummy',
  'Dopplezon',
  'Valkyrie',
  'Dummy',
  'Iron Wolf',
  'Balrog',
  'PitLord',
  'VenomLord',
  'NecroSkeleton',
  'NecroMage',
  'Griswold',
  'compellingorb',
  'tyrael',
  'youngdiablo',
  'a trap',
  'Dummy',
  'LightningSpire',
  'FireTower',
  'Slinger',
  'SpearCat',
  'NightSlinger',
  'HellSlinger',
  'Dummy',
  'Dummy',
  'ReturnedMage',
  'BoneMage',
  'BaalColdMage',
  'HorrorMage',
  'ReturnedMage',
  'BoneMage',
  'BurningDeadMage',
  'HorrorMage',
  'ReturnedMage',
  'BoneMage',
  'BurningDeadMage',
  'HorrorMage',
  'Hell Bovine',
  '',
  '',
  'SpearCat',
  'NightSlinger',
  'RatMan',
  'Fetish',
  'Flayer',
  'SoulKiller',
  'StygianDoll',
  'Dummy',
  'The Smith',
  'TrappedSoul',
  'TrappedSoul',
  'Jamella',
  'Izual',
  'RatMan',
  'Malachai',
  'The Feature Creep',
  'Wake of Destruction',
  'Charged Bolt Sentry',
  'Lightning Sentry',
  'Blade Creeper',
  'Invis Pet',
  'Inferno Sentry',
  'Death Sentry',
  'Shadow Warrior',
  'Shadow Master',
  'Druid Hawk',
  'Druid Spirit Wolf',
  'Druid Fenris',
  'Spirit of Barbs',
  'Heart of Wolverine',
  'Oak Sage',
  'Druid Plague Poppy',
  'Druid Cycle of Life',
  'Vine Creature',
  'Druid Bear',
  'Eagle',
  'Wolf',
  'Bear',
  'Barricade Door',
  'Barricade Door',
  'Prison Door',
  'Barricade Tower',
  'RotWalker',
  'ReanimatedHorde',
  'ProwlingDead',
  'UnholyCorpse',
  'DefiledWarrior',
  'Siege Beast',
  'CrushBiest',
  'BloodBringer',
  'GoreBearer',
  'DeamonSteed',
  'SnowYeti1',
  'SnowYeti2',
  'SnowYeti3',
  'SnowYeti4',
  'WolfRider1',
  'WolfRider2',
  'WolfRider3',
  'Minionexp',
  'Slayerexp',
  'IceBoar',
  'FireBoar',
  'HellSpawn',
  'IceSpawn',
  'GreaterHellSpawn',
  'GreaterIceSpawn',
  'FanaticMinion',
  'BerserkSlayer',
  'ConsumedIceBoar',
  'ConsumedFireBoar',
  'FrenziedHellSpawn',
  'FrenziedIceSpawn',
  'InsaneHellSpawn',
  'InsaneIceSpawn',
  'Succubusexp',
  'VileTemptress',
  'StygianHarlot',
  'Hell Temptress',
  'Blood Temptress',
  'Dominus',
  'VileWitch',
  'StygianFury',
  'Blood Witch',
  'Hell Witch',
  'OverSeer',
  'Lasher',
  'OverLord',
  'BloodBoss',
  'HellWhip',
  'MinionSpawner',
  'MinionSlayerSpawner',
  'MinionIce/fireBoarSpawner',
  'MinionIce/fireBoarSpawner',
  'Minionice/hellSpawnSpawner',
  'MinionIce/fireBoarSpawner',
  'MinionIce/fireBoarSpawner',
  'Minionice/hellSpawnSpawner',
  'Imp1',
  'Imp2',
  'Imp3',
  'Imp4',
  'Imp5',
  'CatapultS',
  'CatapultE',
  'CatapultSiege',
  'CatapultW',
  'Frozen Horror1',
  'Frozen Horror2',
  'Frozen Horror3',
  'Frozen Horror4',
  'Frozen Horror5',
  'Blood Lord1',
  'Blood Lord2',
  'Blood Lord3',
  'Blood Lord4',
  'Blood Lord5',
  'Larzuk',
  'Drehya',
  'Malah',
  'Nihlathak Town',
  'Qual-Kehk',
  'Catapult Spotter S',
  'Catapult Spotter E',
  'Catapult Spotter Siege',
  'Catapult Spotter W',
  'DeckardCain',
  'tyrael',
  'Act 5 Combatant',
  'Act 5 Combatant',
  'Barricade Wall Right',
  'Barricade Wall Left',
  'Nihlathak',
  'Drehya',
  'Evil hut',
  'Death Mauler1',
  'Death Mauler2',
  'Death Mauler3',
  'Death Mauler4',
  'Death Mauler5',
  'POW',
  'Act 5 Townguard',
  'Act 5 Townguard',
  'Ancient Statue 1',
  'Ancient Statue 2',
  'Ancient Statue 3',
  'Ancient Barbarian 1',
  'Ancient Barbarian 2',
  'Ancient Barbarian 3',
  'Baal Throne',
  'Baal Crab',
  'Baal Taunt',
  'Putrid Defiler1',
  'Putrid Defiler2',
  'Putrid Defiler3',
  'Putrid Defiler4',
  'Putrid Defiler5',
  'Pain Worm1',
  'Pain Worm2',
  'Pain Worm3',
  'Pain Worm4',
  'Pain Worm5',
  'dummy',
  'Council Member',
  'VenomLord',
  'Baal Crab to Stairs',
  'dummy',
  'dummy',
  'Baal Tentacle',
  'Baal Tentacle',
  'Baal Tentacle',
  'Baal Tentacle',
  'Baal Tentacle',
  'dummy',
  'dummy',
  'dummy',
  'Baal Crab Clone',
  'Baals Minion',
  'Baals Minion',
  'Baals Minion',
  'dummy',
  'BurningDeadArcher',
  'BoneArcher',
  'BurningDeadArcher',
  'ReturnedArcher',
  'HorrorArcher',
  'Afflicted',
  'Tainted',
  'Misshapen',
  'Disfigured',
  'Damned',
  'MoonClan',
  'NightClan',
  'HellClan',
  'BloodClan',
  'DeathClan',
  'FoulCrow',
  'BloodHawk',
  'BlackRaptor',
  'CloudStalker',
  'ClawViper',
  'PitViper',
  'Salamander',
  'TombViper',
  'SerpentMagus',
  'Marauder',
  'Infidel',
  'SandRaider',
  'Invader',
  'Assailant',
  'Death Mauler1',
  'QuillRat',
  'SpikeFiend',
  'RazorSpine',
  'CarrionBird',
  'ThornedHulk',
  'Slinger',
  'Slinger',
  'Slinger',
  'VileArcher',
  'DarkArcher',
  'VileLancer',
  'DarkLancer',
  'BlackLancer',
  'Blunderbore',
  'Mauler',
  'ReturnedMage',
  'BurningDeadMage',
  'ReturnedMage',
  'HorrorMage',
  'BoneMage',
  'HorrorMage',
  'HorrorMage',
  'Huntress',
  'SaberCat',
  'CaveLeaper',
  'TombCreeper',
  'Ghost',
  'Wraith',
  'Specter',
  'Succubusexp',
  'Hell Temptress',
  'Dominus',
  'Hell Witch',
  'VileWitch',
  'Gloam',
  'BlackSoul',
  'BurningSoul',
  'Carver',
  'Devilkin',
  'DarkOne',
  'CarverShaman',
  'DevilkinShaman',
  'DarkShaman',
  'BoneWarrior',
  'Returned',
  'Gloombat',
  'Fiend',
  'Blood Lord1',
  'Blood Lord4',
  'Scarab',
  'SteelWeevil',
  'Flayer',
  'StygianDoll',
  'SoulKiller',
  'Flayer',
  'StygianDoll',
  'SoulKiller',
  'FlayerShaman',
  'StygianDollShaman',
  'SoulKillerShaman',
  'TempleGuard',
  'TempleGuard',
  'Guardian',
  'Unraveler',
  'Horadrim Ancient',
  'Horadrim Ancient',
  'Zealot',
  'Zealot',
  'Heirophant',
  'Heirophant',
  'Grotesque',
  'FleshSpawner',
  'GrotesqueWyrm',
  'FleshBeast',
  'WorldKiller',
  'WorldKillerYoung',
  'WorldKillerEgg',
  'Slayerexp',
  'HellSpawn',
  'GreaterHellSpawn',
  'Arach',
  'Balrog',
  'PitLord',
  'Imp1',
  'Imp4',
  'Undead StygianDoll',
  'Undead SoulKiller',
  'Strangler',
  'StormCaster',
  'MawFiend',
  'BloodLord',
  'GhoulLord',
  'DarkLord',
  'UnholyCorpse',
  'DoomKnight',
  'DoomKnight',
  'OblivionKnight',
  'OblivionKnight',
  'Cadaver',
  'Mephisto',
  'Diablo',
  'izual',
  'Lilith',
  'Duriel',
  'Baal Crab',
  'Evil hut',
  'Dummy',
  'PitLord',
  'OblivionKnight',
  'Imp4',
  'HellSwarm',
  'WorldKiller',
  'Arach',
  'SteelWeevil',
  'Hell Temptress',
  'VileWitch',
  'FleshHunter',
  'DarkArcher',
  'BlackLancer',
  'HellWhip',
  'Returned',
  'HorrorArcher',
  'BurningDeadMage',
  'HorrorMage',
  'BoneMage',
  'HorrorMage',
  'DarkLord',
  'Specter',
  'BurningSoul',
  'Hydra',
  'Hydra',
  'Hydra',
  'Hydra',
  'Hydra',
  'Hydra',
  'Baals Minion',
  'Death Mauler1',
  'UnholyCorpse',
  'StormCaster',
  'OblivionKnight',
  'DoomKnight',
  'TempleGuard',
  'Blunderbore',
  'Fiend',
  'Council Member',
  'Zealot',
  'SoulKillerShaman',
  'Heirophant',
  'HorrorArcher',
  'DarkLord',
  'BurningDeadMage',
  'SnowYeti4',
  'HellWhip',
  'Hell Temptress',
  'SerpentMagus',
  'VenomLord',
  'HellSpawn',
  'SoulKiller',
  'SoulKiller',
  'Blunderbore',
  'Imp5',
  'SpiderMagus',
  'DeathClan',
  'StormCaster',
  'MawFiend',
  'OblivionKnight',
  'JungleUrchin',
  'Banished',
  'Frozen Horror5',
  'DeamonSteed',
  'InsaneIceSpawn',
  'Putrid Defiler5',
  'BloodWing',
  'Spikefist',
  'BlackSoul',
  'FleshArcher',
  'WarpedShaman',
  'Tainted',
  'PlagueBearer',
  'DarkShape',
  'Cadaver',
  'AlbinoRoach',
  'Assailant',
  'SerpentMagus',
  'GargantuanBeast',
  'Horror',
  'Grotesque',
  'Slime Prince',
  'Heirophant',
  'Banished',
  'RazorPitDemon',
  'Blood Temptress',
  'Undead SoulKiller',
  'HellSwarm',
  'WorldKiller',
  'FleshLancer',
  'TempleGuard',
  'Slinger',
  'punchingbag',
  'Dummy',
  'Shadow Master',
  'Decayed',
  'Ghost',
  'Decayed',
  'HungryDead',
  'FanaticMinion',
  'Dummy',
  'Druid Hawk',
  'Mauler',
  'Spikefist',
  'Skeleton',
  'Death Mauler5',
  'FlyingScimitar',
  'Druid Hawk',
  'Druid Hawk',
  'Druid Hawk',
  'Spikefist',
  'FleshArcher',
  'OblivionKnight',
  'DevilCat',
  'valkyrie',
  'bonewall',
  'Skeleton',
  'Blood Temptress',
  'GhoulLord',
  'Dummy',
  'Shadow Master',
  'Hydra',
  '',
  '',
  'SacLamb',
  'Shadow Master',
  'Urdar',
  'DarkLord',
  'Death Mauler4',
  'Blood Lord4',
  'Dopplezon',
  '',
  '',
  'Hydra',
  '',
  '',
  'dcloneminionName',
  'youngdiablo',
  'darkwanderer',
  'dclonearcherName',
];
